import { Role } from "@prisma/client";

export const PERMISSIONS = {
  ADMIN_ACCESS: "admin:access",
  CLINICS_CREATE: "clinics:create",
  CLINICS_READ: "clinics:read",
  CLINICS_UPDATE: "clinics:update",
  CLINICS_DELETE: "clinics:delete",
  CLINICS_SUSPEND: "clinics:suspend",
  USERS_CREATE: "users:create",
  USERS_READ: "users:read",
  USERS_UPDATE: "users:update",
  USERS_DELETE: "users:delete",
  SETTINGS_READ: "settings:read",
  SETTINGS_UPDATE: "settings:update",
  SESSIONS_READ: "sessions:read",
  SESSIONS_REVOKE: "sessions:revoke",
  PATIENTS_CREATE: "patients:create",
  PATIENTS_READ: "patients:read",
  PATIENTS_UPDATE: "patients:update",
  PATIENTS_DELETE: "patients:delete",
  DOCTORS_CREATE: "doctors:create",
  DOCTORS_READ: "doctors:read",
  DOCTORS_UPDATE: "doctors:update",
  DOCTORS_DELETE: "doctors:delete",
  DOCTORS_SCHEDULE: "doctors:schedule",
  DOCTORS_LEAVE: "doctors:leave",
  APPOINTMENTS_CREATE: "appointments:create",
  APPOINTMENTS_READ: "appointments:read",
  APPOINTMENTS_UPDATE: "appointments:update",
  APPOINTMENTS_DELETE: "appointments:delete",
  TREATMENTS_CREATE: "treatments:create",
  TREATMENTS_READ: "treatments:read",
  TREATMENTS_UPDATE: "treatments:update",
  PRESCRIPTIONS_CREATE: "prescriptions:create",
  PRESCRIPTIONS_READ: "prescriptions:read",
  NOTIFICATIONS_READ: "notifications:read",
  NOTIFICATIONS_UPDATE: "notifications:update",
} as const;

export type PermissionName = (typeof PERMISSIONS)[keyof typeof PERMISSIONS];

export const ALL_PERMISSIONS: {
  name: PermissionName;
  description: string;
}[] = [
  { name: PERMISSIONS.ADMIN_ACCESS, description: "Access platform admin area" },
  { name: PERMISSIONS.CLINICS_CREATE, description: "Create clinics" },
  { name: PERMISSIONS.CLINICS_READ, description: "View clinics" },
  { name: PERMISSIONS.CLINICS_UPDATE, description: "Edit clinics" },
  { name: PERMISSIONS.CLINICS_DELETE, description: "Delete clinics" },
  { name: PERMISSIONS.CLINICS_SUSPEND, description: "Suspend or activate clinics" },
  { name: PERMISSIONS.USERS_CREATE, description: "Create users" },
  { name: PERMISSIONS.USERS_READ, description: "View users" },
  { name: PERMISSIONS.USERS_UPDATE, description: "Edit users" },
  { name: PERMISSIONS.USERS_DELETE, description: "Delete users" },
  { name: PERMISSIONS.SETTINGS_READ, description: "View clinic settings" },
  { name: PERMISSIONS.SETTINGS_UPDATE, description: "Update clinic settings" },
  { name: PERMISSIONS.SESSIONS_READ, description: "View active sessions" },
  { name: PERMISSIONS.SESSIONS_REVOKE, description: "Revoke active sessions" },
  { name: PERMISSIONS.PATIENTS_CREATE, description: "Create patients" },
  { name: PERMISSIONS.PATIENTS_READ, description: "View patients" },
  { name: PERMISSIONS.PATIENTS_UPDATE, description: "Edit patients" },
  { name: PERMISSIONS.PATIENTS_DELETE, description: "Delete patients" },
  { name: PERMISSIONS.DOCTORS_CREATE, description: "Create doctors" },
  { name: PERMISSIONS.DOCTORS_READ, description: "View doctors" },
  { name: PERMISSIONS.DOCTORS_UPDATE, description: "Edit doctors" },
  { name: PERMISSIONS.DOCTORS_DELETE, description: "Delete doctors" },
  { name: PERMISSIONS.DOCTORS_SCHEDULE, description: "Manage doctor schedules" },
  { name: PERMISSIONS.DOCTORS_LEAVE, description: "Manage doctor leaves" },
  { name: PERMISSIONS.APPOINTMENTS_CREATE, description: "Create appointments" },
  { name: PERMISSIONS.APPOINTMENTS_READ, description: "View appointments" },
  { name: PERMISSIONS.APPOINTMENTS_UPDATE, description: "Update appointments" },
  { name: PERMISSIONS.APPOINTMENTS_DELETE, description: "Delete appointments" },
  { name: PERMISSIONS.TREATMENTS_CREATE, description: "Create treatments" },
  { name: PERMISSIONS.TREATMENTS_READ, description: "View treatments" },
  { name: PERMISSIONS.TREATMENTS_UPDATE, description: "Update treatments" },
  { name: PERMISSIONS.PRESCRIPTIONS_CREATE, description: "Create prescriptions" },
  { name: PERMISSIONS.PRESCRIPTIONS_READ, description: "View prescriptions" },
  { name: PERMISSIONS.NOTIFICATIONS_READ, description: "Read notifications" },
  { name: PERMISSIONS.NOTIFICATIONS_UPDATE, description: "Update notifications" },
];

export const DEFAULT_ROLE_PERMISSIONS: Record<Role, PermissionName[]> = {
  SUPER_ADMIN: ALL_PERMISSIONS.map((p) => p.name),
  CLINIC_ADMIN: [
    PERMISSIONS.USERS_CREATE,
    PERMISSIONS.USERS_READ,
    PERMISSIONS.USERS_UPDATE,
    PERMISSIONS.USERS_DELETE,
    PERMISSIONS.SETTINGS_READ,
    PERMISSIONS.SETTINGS_UPDATE,
    PERMISSIONS.SESSIONS_READ,
    PERMISSIONS.SESSIONS_REVOKE,
    PERMISSIONS.PATIENTS_CREATE,
    PERMISSIONS.PATIENTS_READ,
    PERMISSIONS.PATIENTS_UPDATE,
    PERMISSIONS.PATIENTS_DELETE,
    PERMISSIONS.DOCTORS_CREATE,
    PERMISSIONS.DOCTORS_READ,
    PERMISSIONS.DOCTORS_UPDATE,
    PERMISSIONS.DOCTORS_DELETE,
    PERMISSIONS.DOCTORS_SCHEDULE,
    PERMISSIONS.DOCTORS_LEAVE,
    PERMISSIONS.APPOINTMENTS_CREATE,
    PERMISSIONS.APPOINTMENTS_READ,
    PERMISSIONS.APPOINTMENTS_UPDATE,
    PERMISSIONS.APPOINTMENTS_DELETE,
    PERMISSIONS.TREATMENTS_CREATE,
    PERMISSIONS.TREATMENTS_READ,
    PERMISSIONS.TREATMENTS_UPDATE,
    PERMISSIONS.PRESCRIPTIONS_CREATE,
    PERMISSIONS.PRESCRIPTIONS_READ,
    PERMISSIONS.NOTIFICATIONS_READ,
    PERMISSIONS.NOTIFICATIONS_UPDATE,
  ],
  DOCTOR: [
    PERMISSIONS.PATIENTS_CREATE,
    PERMISSIONS.PATIENTS_READ,
    PERMISSIONS.PATIENTS_UPDATE,
    PERMISSIONS.DOCTORS_READ,
    PERMISSIONS.DOCTORS_UPDATE,
    PERMISSIONS.DOCTORS_SCHEDULE,
    PERMISSIONS.DOCTORS_LEAVE,
    PERMISSIONS.APPOINTMENTS_CREATE,
    PERMISSIONS.APPOINTMENTS_READ,
    PERMISSIONS.APPOINTMENTS_UPDATE,
    PERMISSIONS.TREATMENTS_CREATE,
    PERMISSIONS.TREATMENTS_READ,
    PERMISSIONS.TREATMENTS_UPDATE,
    PERMISSIONS.PRESCRIPTIONS_CREATE,
    PERMISSIONS.PRESCRIPTIONS_READ,
    PERMISSIONS.NOTIFICATIONS_READ,
    PERMISSIONS.NOTIFICATIONS_UPDATE,
  ],
  RECEPTIONIST: [
    PERMISSIONS.SETTINGS_READ,
    PERMISSIONS.USERS_READ,
    PERMISSIONS.USERS_CREATE,
    PERMISSIONS.USERS_UPDATE,
    PERMISSIONS.PATIENTS_CREATE,
    PERMISSIONS.PATIENTS_READ,
    PERMISSIONS.PATIENTS_UPDATE,
    PERMISSIONS.DOCTORS_READ,
    PERMISSIONS.DOCTORS_SCHEDULE,
    PERMISSIONS.APPOINTMENTS_CREATE,
    PERMISSIONS.APPOINTMENTS_READ,
    PERMISSIONS.APPOINTMENTS_UPDATE,
    PERMISSIONS.NOTIFICATIONS_READ,
    PERMISSIONS.NOTIFICATIONS_UPDATE,
  ],
  PATIENT: [
    PERMISSIONS.PATIENTS_READ,
    PERMISSIONS.PATIENTS_UPDATE,
    PERMISSIONS.DOCTORS_READ,
    PERMISSIONS.APPOINTMENTS_CREATE,
    PERMISSIONS.APPOINTMENTS_READ,
    PERMISSIONS.APPOINTMENTS_UPDATE,
    PERMISSIONS.TREATMENTS_READ,
    PERMISSIONS.PRESCRIPTIONS_READ,
    PERMISSIONS.NOTIFICATIONS_READ,
    PERMISSIONS.NOTIFICATIONS_UPDATE,
  ],
};

export function roleHasPermission(
  role: Role,
  permission: PermissionName,
  rolePermissionMap?: Map<Role, Set<string>>
): boolean {
  if (rolePermissionMap) {
    return rolePermissionMap.get(role)?.has(permission) ?? false;
  }
  return DEFAULT_ROLE_PERMISSIONS[role]?.includes(permission) ?? false;
}

export function roleHasAnyPermission(
  role: Role,
  permissions: PermissionName[],
  rolePermissionMap?: Map<Role, Set<string>>
): boolean {
  return permissions.some((p) => roleHasPermission(role, p, rolePermissionMap));
}
